package com.example.schrecknet.sheetdb

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class CharacterSheet(
    @PrimaryKey val name: String,
    var player: String,
    var chronicle: String,
    var concept: String,
    var ambition: String,
    var predator: String,
    var sire: String,
    var clan: String,
    var generation: Int,
    var strength: Int,
    var dexterity: Int,
    var stamina: Int,
    var charisma: Int,
    var manipulation: Int,
    var composure: Int,
    var intelligence: Int,
    var wits: Int,
    var resolve: Int,
    var athletics: Int,
    var brawl: Int,
    var craft: Int,
    var drive: Int,
    var firearms: Int,
    var melee: Int,
    var larceny: Int,
    var stealth: Int,
    var survival: Int,
    var animalKen: Int,
    var etiquette: Int,
    var insight: Int,
    var intimidation: Int,
    var leadership: Int,
    var performance: Int,
    var persuasion: Int,
    var streetwise: Int,
    var subterfuge: Int,
    var academics: Int,
    var awareness: Int,
    var finance: Int,
    var investigation: Int,
    var medicine: Int,
    var occult: Int,
    var politics: Int,
    var science: Int,
    var technology: Int,
    var chronicleTenets: String,
    var touchstonesAndConvictions: String,
    var clanBane: String,
    var health: SlotsBar,
    var willpower: SlotsBar,
    var bloodPotency: Int,
    var bloodSurges: Int,
    var mendAmount: Int,
    var powerBonus: Int,
    var rouseReRoll: Int,
    var feedingPenaly: Int,
    var baneSeverity: Int,
    var resonance: String,
    var hunting: String,
    var expTotal: Int,
    var expSpent: Int,
    var hunger: Int
)
