package com.example.schrecknet.sheetdb

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class CharacterSheet(
    @PrimaryKey var name: String,
    val player : String,
    val chronicle: String,
    val concept: String,
    val ambition: String,
    val predator: String,
    val sire: String,
    val clan: String,
    val generation: String,
    val strength: Int,
    val dexterity: Int,
    val stamina: Int,
    val charisma: Int,
    val manipulation: Int,
    val composure: Int,
    val intelligence: Int,
    val wits: Int,
    val resolve: Int,
    val athletics: Int,
    val brawl: Int,
    val craft: Int,
    val drive: Int,
    val firearms: Int,
    val melee: Int,
    val larceny: Int,
    val stealth: Int,
    val survival: Int,
    val animalKen: Int,
    val etiquette: Int,
    val insight: Int,
    val intimidation: Int,
    val leadership: Int,
    val performance: Int,
    val persuasion: Int,
    val streetwise: Int,
    val subterfuge: Int,
    val academics: Int,
    val awareness: Int,
    val finance: Int,
    val investigation: Int,
    val medicine: Int,
    val occult: Int,
    val politics: Int,
    val science: Int,
    val technology: Int,
    val chronicleTenets: String,
    val touchstonesAndConvictions: String,
    val clanBane: String,
    val totalHealth: Int,
    val superficialDamageHealth: Int,
    val aggravatedDamageHealth: Int,
    val totalWillpower: Int,
    val superficialDamageWillpower: Int,
    val aggravatedDamageWillpower: Int,
    val totalHumanity: Int,
    val damageHumanity: Int,
    val bloodPotency: Int,
    val bloodSurges: String,
    val mendAmount: String,
    val powerBonus: String,
    val rouseReRoll: String,
    val feedingPenaly: String,
    val baneSeverity: String,
    val resonance: String,
    val hunting: String,
    val expTotal: Int,
    val expSpent: Int,
    val hunger: Int
)
